### ISSUE TITLE
ValueError: Mixed precision training with AMP or APEX

### ISSUE THREAD

**Issue by mwitiderrick** [neuralmagic/sparseml#1134]
Running 
```
!sparseml.transformers.text_classification \
    --output_dir models/teacher \
    --model_name_or_path "zoo:nlp/masked_language_modeling/bert-base/pytorch/huggingface/wikipedia_bookcorpus/base-none" \
    --recipe "zoo:nlp/masked_language_modeling/bert-base/pytorch/huggingface/wikipedia_bookcorpus/base-none?recipe_type=transfer-text_classification" \
    --recipe_args '{"init_lr":0.00003}' \
    --task_name sst2 \
    --max_seq_length 128 \
    --per_device_train_batch_size 32 --per_device_eval_batch_size 32 \
    --do_train --do_eval --evaluation_strategy epoch --fp16  \
    --save_strategy epoch --save_total_limit 1
```
from https://docs.neuralmagic.com/get-started/transfer-a-sparsified-model/nlp-text-classification gives this error 
```
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
  "message": {
    "message": "ValueError: Mixed precision training with AMP or APEX (`--fp16` or `--bf16`) and half precision evaluation (`--fp16_full_eval` or `--bf16_full_eval`) can only be used on CUDA devices.",
    "extraInfo": {
      "py_callstack": [
        "  File \"/usr/local/bin/sparseml.transformers.text_classification\", line 8, in <module>\n    sys.exit(main())\n",
        "  File \"/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 370, in wrapper\n    error_handler.record_exception(e)\n",
        "  File \"/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/multiprocessing/errors/error_handler.py\", line 86, in record_exception\n    _write_error(e, self._get_error_file_path())\n",
        "  File \"/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/multiprocessing/errors/error_handler.py\", line 26, in _write_error\n    \"py_callstack\": traceback.format_stack(),\n"
      ],
      "timestamp": "1667897679"
    }
  }
}
Traceback (most recent call last):
  File "/usr/local/bin/sparseml.transformers.text_classification", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 361, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sparseml/transformers/text_classification.py", line 314, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/usr/local/lib/python3.7/dist-packages/transformers/hf_argparser.py", line 215, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 95, in __init__
  File "/usr/local/lib/python3.7/dist-packages/transformers/training_args.py", line 869, in __post_init__
    "Mixed precision training with AMP or APEX (`--fp16` or `--bf16`) and half precision evaluation (`--fp16_full_eval` or `--bf16_full_eval`) can only be used on CUDA devices."
ValueError: Mixed precision training with AMP or APEX (`--fp16` or `--bf16`) and half precision evaluation (`--fp16_full_eval` or `--bf16_full_eval`) can only be used on CUDA devices.
```

**Comment by bfineran** [comment]
@mwitiderrick looks like CUDA isn't enabled with pytorch for the device this was run on.  Have you been able to resolve this on your environment?

**Comment by mwitiderrick** [comment]
> sparseml.transformers.text_classification \
>     --output_dir models/teacher \
>     --model_name_or_path "zoo:nlp/masked_language_modeling/bert-base/pytorch/huggingface/wikipedia_bookcorpus/base-none" \
>     --recipe "zoo:nlp/masked_language_modeling/bert-base/pytorch/huggingface/wikipedia_bookcorpus/base-none?recipe_type=transfer-text_classification" \
>     --recipe_args '{"init_lr":0.00003}' \
>     --task_name sst2 \
>     --max_seq_length 128 \
>     --per_device_train_batch_size 32 --per_device_eval_batch_size 32 \
>     --do_train --do_eval --evaluation_strategy epoch --fp16  \
>     --save_strategy epoch --save_total_limit 1

**Comment by mwitiderrick** [comment]
Tried this now and the error is gone
