### ISSUE TITLE
Error while traning using spaseml

### ISSUE THREAD

**Issue by naveen715** [neuralmagic/sparseml#1524]
while using sparseml to train my yolov8 object detection model following error was thrown
!pip install sparseml[ultralytics]
!sparseml.ultralytics.train --task=detect --pretrained --model=./content/drive/MyDrive/YOLOV8/datasets/runs/detect/train/weights/last.pt --data=/content/drive/MyDrive/YOLOV8/datasets/drones-8/data.yaml --recipe yolov8-wip.yaml --batch 4 --epochs 70
Error
/bin/bash: sparseml.ultralytics.train: command not found

**Comment by naveen715** [comment]
> 

Name: sparseml
Version: 1.4.4
Summary: Libraries for applying sparsification recipes to neural networks with a few lines of code, enabling faster and smaller models
Home-page: https://github.com/neuralmagic/sparseml
Author: Neuralmagic, Inc.
Author-email: [support@neuralmagic.com](mailto:support@neuralmagic.com)
License: Apache
Location: /usr/local/lib/python3.9/dist-packages
Requires: click, GPUtil, ipywidgets, jupyter, matplotlib, merge-args, numpy, onnx, packaging, pandas, progressbar2, protobuf, psutil, pydantic, pyyaml, requests, scikit-image, scikit-learn, scipy, setuptools, sparsezoo, toposort, tqdm
Required-by:
this was the output for pip show sparseml 
sparseml has no 1.5 variant last is 1.4.4

**Comment by rahul-tuli** [comment]
We do not yet have a 1.5 release for sparseml; however you could try installing sparseml-nightly>1.5 which should allow you to use this pathway!

**Comment by naveen715** [comment]
Thank you for replying i used sparseml-nightly but when i am trying to train a model again its giving error 
Command to train
!sparseml.ultralytics.train --task=detect --pretrained --model=/content/drive/MyDrive/YOLOV8/datasets/runs/detect/train/weights/yolov88888.pt --data=/content/drive/MyDrive/YOLOV8/datasets/drones-8/data.yaml --recipe yolov8-wip.yaml --batch 4 --epochs 70


/usr/local/lib/python3.9/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.9/dist-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Ultralytics YOLOv8.0.30 🚀 Python-3.9.16 torch-1.13.1+cu117 CPU
yolo/engine/trainer: recipe=yolov8-wip.yaml, recipe_args=None, datasets_dir=None, task=detect, mode=train, model=/content/drive/MyDrive/YOLOV8/datasets/runs/detect/train/weights/yolov88888.pt, data=/content/drive/MyDrive/YOLOV8/datasets/drones-8/data.yaml, epochs=70, patience=50, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, min_memory=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, save_dir=runs/detect/train
Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...
100% 755k/755k [00:00<00:00, 16.2MB/s]

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.Conv                  [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.Conv                  [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.C2f                   [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.Conv                  [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.C2f                   [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.Conv                  [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.C2f                   [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.Conv                  [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.C2f                   [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.SPPF                  [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.C2f                   [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.C2f                   [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.Conv                  [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.C2f                   [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.Conv                  [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.C2f                   [960, 576, 2]                 
 22        [15, 18, 21]  1   3776275  ultralytics.nn.modules.Detect                [1, [192, 384, 576]]          
Model summary: 295 layers, 25856899 parameters, 25856883 gradients, 79.1 GFLOPs

Transferred 475/475 items from pretrained weights
2023-04-20 05:40:39.440872: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core._multiarray_umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core._multiarray_umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core._multiarray_umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sparseml.ultralytics.train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sparseml/yolov8/train.py", line 229, in main
    model.train(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sparseml/yolov8/trainers.py", line 776, in train
    self.trainer.train()
  File "/usr/local/lib/python3.9/dist-packages/sparseml/yolov8/trainers.py", line 159, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/trainer.py", line 250, in _do_train
    self._setup_train(rank, world_size)
  File "/usr/local/lib/python3.9/dist-packages/sparseml/yolov8/trainers.py", line 273, in _setup_train
    super()._setup_train(rank, world_size)
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/trainer.py", line 200, in _setup_train
    self.run_callbacks("on_pretrain_routine_start")
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/trainer.py", line 164, in run_callbacks
    callback(self)
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/utils/callbacks/tensorboard.py", line 15, in on_pretrain_routine_start
    writer = SummaryWriter(str(trainer.save_dir))
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/tensorboard/writer.py", line 247, in __init__
    self._get_file_writer()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/tensorboard/writer.py", line 277, in _get_file_writer
    self.file_writer = FileWriter(
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/tensorboard/writer.py", line 76, in __init__
    self.event_writer = EventFileWriter(
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/lazy.py", line 50, in load_once
    module = load_fn()
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/__init__.py", line 45, in tf
    import tensorflow
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/data/__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/data/experimental/__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/data/experimental/service/__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 22, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/data/util/structure.py", line 22, in <module>
    from tensorflow.python.data.util import nest
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/data/util/nest.py", line 34, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/sparse_tensor.py", line 25, in <module>
    from tensorflow.python.framework import constant_op
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/eager/execute.py", line 21, in <module>
    from tensorflow.python.framework import dtypes
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/dtypes.py", line 37, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

**Comment by rahul-tuli** [comment]
Hi @naveen715 thanks for getting back to us, could you send over some more info that with help us take a finer look at your issue:
 - brief summary
 - OS/Environment details (Could you also send over the output from `pip list`)
 - steps to reproduce (s.t.r.)

**Comment by jeanniefinks** [comment]
Hi @naveen715 
Following up here on our request; thank you so much!
Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
Hello again @naveen715 
This is another thread that has had some time without a response. We're going to go ahead and close out this issue. Again, if you would like to continue the conversation, definitely re-open the issue and we'd be glad to help. 
Regards, Jeannie / Neural Magic
