### ISSUE TITLE
ImportError: cannot import name 'override_model_input_shape' from 'sparseml.onnx.utils'

### ISSUE THREAD

**Issue by max190** [neuralmagic/sparseml#1547]
Bug:
Installed sparseml latest version and ran the command:
sparseml.yolov5.train --help
Got error:
ImportError: cannot import name 'override_model_input_shape' from 'sparseml.onnx.utils'

**Environment**
Include all relevant environment information:
1. Ubuntu20.04
2. python 3.8.16
3. Sparseml version 1.4.2
4. pytorch version 1.12.1
5. onnx version 1.10.2
6. Pyotch was installed using command: conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge
7. Sparseml installed using command: pip install sparseml

Error log:
Traceback (most recent call last):
  File "/local/home/chandnam/anaconda3/envs/sparseml/bin/sparseml.yolov5.train", line 5, in <module>
    from sparseml.yolov5.scripts import train
  File "/local/home/chandnam/anaconda3/envs/sparseml/lib/python3.8/site-packages/sparseml/yolov5/scripts.py", line 17, in <module>
    from yolov5.export import export_run
  File "/local/home/chandnam/anaconda3/envs/sparseml/lib/python3.8/site-packages/yolov5/export.py", line 76, in <module>
    from yolov5.utils.neuralmagic import apply_recipe_one_shot, export_sample_inputs_outputs, neuralmagic_onnx_export
  File "/local/home/chandnam/anaconda3/envs/sparseml/lib/python3.8/site-packages/yolov5/utils/neuralmagic/__init__.py", line 1, in <module>
    from .sparsification_manager import *
  File "/local/home/chandnam/anaconda3/envs/sparseml/lib/python3.8/site-packages/yolov5/utils/neuralmagic/sparsification_manager.py", line 12, in <module>
    from yolov5.utils.neuralmagic.utils import ALMOST_ONE, QAT_BATCH_SCALE, ToggleableModelEMA, load_ema, nm_log_console
  File "/local/home/chandnam/anaconda3/envs/sparseml/lib/python3.8/site-packages/yolov5/utils/neuralmagic/utils.py", line 12, in <module>
    from sparseml.onnx.utils import override_model_input_shape
ImportError: cannot import name 'override_model_input_shape' from 'sparseml.onnx.utils' (/local/home/chandnam/anaconda3/envs/sparseml/lib/python3.8/site-packages/sparseml/onnx/utils/__init__.py)
Neural Magic's latest package version check raised an exception. To turn off set the following in the environment NM_VERSION_CHECK=false Exception: Exception occured in the Neural Magic's internal version-api check
HTTPSConnectionPool(host='api.neuralmagic.com', port=443): Max retries exceeded with url: /packages/check-latest?packages=sparseml&integrations=None&versions=1.4.2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

**Comment by jeanniefinks** [comment]
Hi @max190 
If there are no further questions, we'll close out this issue. Please re-open the issue if you would like to continue the thread, thanks!
Jeannie / Neural Magic
