### ISSUE TITLE
Getting error while training model for yolov8

### ISSUE THREAD

**Issue by SHIVAM3052** [neuralmagic/sparseml#1560]
sparseml.ultralytics.train \
  --model "zoo:cv/detection/yolov8-s/pytorch/ultralytics/coco/pruned65-none" \
  --recipe "zoo:cv/detection/yolov8-s/pytorch/ultralytics/voc/pruned65-none" \
  --data ./dataset/data.yaml \
  --batch 16 \
  --imgsz 640 \
  --patience 0
Traceback (most recent call last):
  File "/home/vision/anaconda3/envs/sparse/bin/sparseml.ultralytics.train", line 8, in <module>
    sys.exit(main())
  File "/home/vision/anaconda3/envs/sparse/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/vision/anaconda3/envs/sparse/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/vision/anaconda3/envs/sparse/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vision/anaconda3/envs/sparse/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/vision/anaconda3/envs/sparse/lib/python3.9/site-packages/sparseml/yolov8/train.py", line 224, in main
    model = SparseYOLO(kwargs["model"])
  File "/home/vision/anaconda3/envs/sparse/lib/python3.9/site-packages/sparseml/yolov8/trainers.py", line 550, in __init__
    super().__init__(model, type)
  File "/home/vision/anaconda3/envs/sparse/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 62, in __init__
    {'.pt': self._load, '.yaml': self._new}[suffix](model)
  File "/home/vision/anaconda3/envs/sparse/lib/python3.9/site-packages/sparseml/yolov8/trainers.py", line 624, in _load
    return super()._load(weights)
  File "/home/vision/anaconda3/envs/sparse/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 92, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/vision/anaconda3/envs/sparse/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 392, in attempt_load_one_weight
    model = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
AttributeError: 'collections.OrderedDict' object has no attribute 'to'

**Comment by scraus** [comment]
Hello! Any updates? I am experiencing the same issue. Please help.
![image](https://github.com/neuralmagic/sparseml/assets/91582176/8559fecf-24c5-415a-8ea1-164d8ca0d828)

**Comment by mgoin** [comment]
Thanks for reporting the issue! We communicated over Slack on this but to close it out, [this PR ](https://github.com/neuralmagic/sparseml/pull/1561) should address the issue and you can simply update your sparseml-nightly version
