### ISSUE TITLE
cannot import name 'load_model'

### ISSUE THREAD

**Issue by kopyl** [neuralmagic/sparseml#1653]
i run: `sparseml.ultralytics.train --model yolov8_v2.pt --recipe yolov8-pq.yaml`

i get:
```
Traceback (most recent call last):
  File "/usr/local/bin/sparseml.ultralytics.train", line 5, in <module>
    from sparseml.yolov8.train import main
  File "/usr/local/lib/python3.10/dist-packages/sparseml/yolov8/train.py", line 18, in <module>
    from sparseml.yolov8.trainers import SparseYOLO
  File "/usr/local/lib/python3.10/dist-packages/sparseml/yolov8/trainers.py", line 30, in <module>
    from sparseml.pytorch.optim.manager import ScheduledModifierManager
  File "/usr/local/lib/python3.10/dist-packages/sparseml/pytorch/__init__.py", line 62, in <module>
    from .framework import detect_framework, framework_info, is_supported
  File "/usr/local/lib/python3.10/dist-packages/sparseml/pytorch/framework/__init__.py", line 24, in <module>
    from .info import *
  File "/usr/local/lib/python3.10/dist-packages/sparseml/pytorch/framework/info.py", line 26, in <module>
    from sparseml.pytorch.sparsification import sparsification_info
  File "/usr/local/lib/python3.10/dist-packages/sparseml/pytorch/sparsification/__init__.py", line 24, in <module>
    from .distillation import *
  File "/usr/local/lib/python3.10/dist-packages/sparseml/pytorch/sparsification/distillation/__init__.py", line 17, in <module>
    from .modifier_distillation import *
  File "/usr/local/lib/python3.10/dist-packages/sparseml/pytorch/sparsification/distillation/modifier_distillation.py", line 24, in <module>
    from sparseml.pytorch.sparsification.distillation.modifier_distillation_base import (
  File "/usr/local/lib/python3.10/dist-packages/sparseml/pytorch/sparsification/distillation/modifier_distillation_base.py", line 30, in <module>
    from sparseml.pytorch.sparsification.modifier import (
  File "/usr/local/lib/python3.10/dist-packages/sparseml/pytorch/sparsification/modifier.py", line 36, in <module>
    from sparseml.pytorch.utils import LOGGING_LEVELS, BaseLogger, LoggerManager
  File "/usr/local/lib/python3.10/dist-packages/sparseml/pytorch/utils/__init__.py", line 24, in <module>
    from .exporter import *
  File "/usr/local/lib/python3.10/dist-packages/sparseml/pytorch/utils/exporter.py", line 37, in <module>
    from sparseml.onnx.utils import ONNXGraph
  File "/usr/local/lib/python3.10/dist-packages/sparseml/onnx/__init__.py", line 24, in <module>
    from .benchmark import *
  File "/usr/local/lib/python3.10/dist-packages/sparseml/onnx/benchmark/__init__.py", line 22, in <module>
    from .info import *
  File "/usr/local/lib/python3.10/dist-packages/sparseml/onnx/benchmark/info.py", line 28, in <module>
    from sparseml.onnx.framework import framework_info as get_framework_info
  File "/usr/local/lib/python3.10/dist-packages/sparseml/onnx/framework/__init__.py", line 24, in <module>
    from .info import *
  File "/usr/local/lib/python3.10/dist-packages/sparseml/onnx/framework/info.py", line 26, in <module>
    from sparseml.onnx.sparsification import sparsification_info
  File "/usr/local/lib/python3.10/dist-packages/sparseml/onnx/sparsification/__init__.py", line 24, in <module>
    from .analyzer import *
  File "/usr/local/lib/python3.10/dist-packages/sparseml/onnx/sparsification/analyzer.py", line 26, in <module>
    from sparseml.onnx.utils import DataLoader, DeepSparseAnalyzeModelRunner, ONNXGraph
  File "/usr/local/lib/python3.10/dist-packages/sparseml/onnx/utils/__init__.py", line 21, in <module>
    from .data import *
  File "/usr/local/lib/python3.10/dist-packages/sparseml/onnx/utils/data.py", line 27, in <module>
    from sparseml.onnx.utils.helpers import (
  File "/usr/local/lib/python3.10/dist-packages/sparseml/onnx/utils/helpers.py", line 31, in <module>
    from sparsezoo.utils import load_model, save_onnx
ImportError: cannot import name 'load_model' from 'sparsezoo.utils' (/usr/local/lib/python3.10/dist-packages/sparsezoo/utils/__init__.py)
```
???

**Comment by bfineran** [comment]
Hi @kopyl what version of sparsezoo do you have installed? If you install nightly this should be fixed

**Comment by bfineran** [comment]
which version of nightly?

**Comment by kopyl** [comment]
> which version of nightly?

Don't use it right now, so don't remember :(

**Comment by jeanniefinks** [comment]
Hi @kopyl 
If you happen to install the latest nightly, and see the same issues, do let us know. Thank you so much!
Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
Hello,
I will close out this issue. Please feel free to re-open this the thread if you want to continue the conversation.
Regards, Jeannie / Neural Magic
