### ISSUE TITLE
Unexpected keyword krgument 'image_size'

### ISSUE THREAD

**Issue by ianfinley89** [neuralmagic/sparseml#1718]
**Describe the bug**
During sparmseml yolov5 transfer learning, once the QAT phase begins, a TypeError occurs within SparsificationManager.rescale_gradient_accumulation() step: 
`got an unexpected keyword argument 'image_size'`

**Expected behavior**
This happens at quantization step 7/8 of the total expected quantization steps given my training arguments:

`!sparseml.yolov5.train \
  --weights "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn" \
  --recipe "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn" \
  --recipe-args '{"num_epochs":80, "quantization_epochs":10}' \
  --data VisDrone.yaml \
  --batch-size 64 \
  --save-period 20 \
  --cfg yolov5s.yaml \
  --cache \
  --hyp hyps/hyp.finetune.yaml`

This should quantize, finish fine-tuning, and then perform the final quantization and pruning to generate the last.pt checkpoint to be exported through ONNX.

**Environment**
Include all relevant environment information:
1. CentOS Linux 7 (Core)"
2. Python 3.10.11
3. SparseML 1.5.3
4. torch: 1.12.1+cu113

- SparseZoo, 1.5.1
- Deepsparse 1.5.3
- numpy 1.21.6
- ONNX 1.12.0:

6. A100 CUDA version 11.3:

**To Reproduce**
Run `!sparseml.yolov5.train \
  --weights "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn" \
  --recipe "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn" \
  --recipe-args '{"num_epochs":80, "quantization_epochs":10}' \
  --data VisDrone.yaml \
  --batch-size 64 \
  --save-period 20 \
  --cfg yolov5s.yaml \
  --cache \
  --hyp hyps/hyp.finetune.yaml`

use a converted VisDrone dataset and configuration file. VisDrone YAML is maintained with Ultralytics at: https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/datasets/VisDrone.yaml

**Errors**

Output and Tracestack:
```
Adjusted gradient clipping threshold to 10.0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      69/79      13.1G    0.06338     0.0395    0.01191        742        640: 1
                 Class     Images  Instances          P          R      mAP50   
                   all        548      38759       0.54      0.212      0.194     0.0949
Neural Magic: Starting QAT phase
Neural Magic: Turning off EMA (not supported with QAT)
Neural Magic: Turning off AMP (not supported with QAT)
Traceback (most recent call last):
  File "/people/finl072/.conda/envs/n_magic/bin/sparseml.yolov5.train", line 8, in <module>
    sys.exit(train())
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/sparseml/yolov5/scripts.py", line 41, in train
    train_run(**vars(opt))
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/yolov5/train.py", line 731, in run
    main(opt)
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/yolov5/train.py", line 631, in main
    train(opt.hyp, opt, device, callbacks)
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/yolov5/train.py", line 314, in train
    new_batch_size, new_accumulate = sparsification_manager.rescale_gradient_accumulation(
TypeError: SparsificationManager.rescale_gradient_accumulation() got an unexpected keyword argument 'image_size'
```

**Comment by ianfinley89** [comment]
I've learned thatthis happens with and without the `--cache` argument

- If I use this training setup it breaks at the QAT phase:

```
!sparseml.yolov5.train \
  --weights "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn" \
  --recipe "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn" \
  --recipe-args '{"num_epochs":12, "quantization_epochs":10}' \
  --data VisDrone.yaml \
  --batch-size 64 \
  --save-period 10 \
  --cfg yolov5s.yaml \
  --hyp hyps/hyp.finetune.yaml
```

```
Adjusted gradient clipping threshold to 10.0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       1/11        13G    0.08168    0.02643    0.01815        437        640: 1
                 Class     Images  Instances          P          R      mAP50   WARNING ⚠️ NMS time limit 6.900s exceeded
                 Class     Images  Instances          P          R      mAP50   WARNING ⚠️ NMS time limit 6.900s exceeded
                 Class     Images  Instances          P          R      mAP50   WARNING ⚠️ NMS time limit 6.900s exceeded
                 Class     Images  Instances          P          R      mAP50   WARNING ⚠️ NMS time limit 6.900s exceeded
                 Class     Images  Instances          P          R      mAP50   WARNING ⚠️ NMS time limit 2.300s exceeded
                 Class     Images  Instances          P          R      mAP50   
                   all        548      38759     0.0232     0.0303     0.0168    0.00501
Neural Magic: Starting QAT phase
Neural Magic: Turning off EMA (not supported with QAT)
Neural Magic: Turning off AMP (not supported with QAT)
Traceback (most recent call last):
  File "/people/finl072/.conda/envs/n_magic/bin/sparseml.yolov5.train", line 8, in <module>
    sys.exit(train())
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/sparseml/yolov5/scripts.py", line 41, in train
    train_run(**vars(opt))
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/yolov5/train.py", line 731, in run
    main(opt)
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/yolov5/train.py", line 631, in main
    train(opt.hyp, opt, device, callbacks)
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/yolov5/train.py", line 314, in train
    new_batch_size, new_accumulate = sparsification_manager.rescale_gradient_accumulation(
TypeError: SparsificationManager.rescale_gradient_accumulation() got an unexpected keyword argument 'image_size'
```

- If I use the `--cache` argument, it also breaks at the QAT phase.

```
!sparseml.yolov5.train \
  --weights "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn" \
  --recipe "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn" \
  --recipe-args '{"num_epochs":12, "quantization_epochs":10}' \
  --data VisDrone.yaml \
  --batch-size 64 \
  --save-period 10 \
  --cfg yolov5s.yaml \
  --cache \
  --hyp hyps/hyp.finetune.yaml
```


```
!sparseml.yolov5.train \
  --weights "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn" \
  --recipe "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn" \
  --recipe-args '{"num_epochs":12, "quantization_epochs":10}' \
  --data VisDrone.yaml \
  --batch-size 64 \
  --save-period 10 \
  --cfg yolov5s.yaml \
  --cache \
  --hyp hyps/hyp.finetune.yaml

Starting training for 12 epochs...
Adjusted gradient clipping threshold to 10.0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       0/11        13G    0.09091    0.02234    0.02223        564        640: 1
                 Class     Images  Instances          P          R      mAP50   
                   all        548      38759    0.00333     0.0256    0.00214   0.000509
Adjusted gradient clipping threshold to 10.0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       1/11        13G    0.08168    0.02643    0.01815        437        640: 1
                 Class     Images  Instances          P          R      mAP50   
                   all        548      38759     0.0215     0.0856      0.026    0.00806
Neural Magic: Starting QAT phase
Neural Magic: Turning off EMA (not supported with QAT)
Neural Magic: Turning off AMP (not supported with QAT)
Traceback (most recent call last):
  File "/people/finl072/.conda/envs/n_magic/bin/sparseml.yolov5.train", line 8, in <module>
    sys.exit(train())
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/sparseml/yolov5/scripts.py", line 41, in train
    train_run(**vars(opt))
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/yolov5/train.py", line 731, in run
    main(opt)
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/yolov5/train.py", line 631, in main
    train(opt.hyp, opt, device, callbacks)
  File "/people/finl072/.conda/envs/n_magic/lib/python3.10/site-packages/yolov5/train.py", line 314, in train
    new_batch_size, new_accumulate = sparsification_manager.rescale_gradient_accumulation(
TypeError: SparsificationManager.rescale_gradient_accumulation() got an unexpected keyword argument 'image_size'
```

**I also discovered that training needs to not start at the same epoch as the QAT phase**
- i.e. num_epochs needs to be > quantization epochs**

**Comment by bfineran** [comment]
Hi @ianfinley89, what version of nm-yolov5 do you have installed? This issue should have been resolved a few releases ago

**Comment by ianfinley89** [comment]
Name: nm-yolov5
Version: 1.5.0.60200

**Comment by ianfinley89** [comment]
I have finally got this working, however, I had to completely uninstall sparseml with the yolov5 extensions (so torch, vision, audio), deepsparse, and nm-yolov5. I had to essentially start back from scratch to get around this issue because upgrading never changed any of my versions/alleviated the problem.
