### ISSUE TITLE
Sparse ML not working for Transformers

### ISSUE THREAD

**Issue by meomeomeome** [neuralmagic/sparseml#2007]
**Describe the bug**

```
OSError: /content/obcq_deployment does not appear to have a file named config.json. Checkout 'https://huggingface.co//content/obcq_deployment/None' for available files.
cp: cannot stat 'deployment/model.onnx': No such file or directory //// always this error when use python sparseml/src/sparseml/transformers/sparsification/obcq/obcq.py HuggingFaceH4/zephyr-7b-beta open-platypus --recipe recipe.yaml --precision bfloat16 --save True 
``` what problem?

After this i do  from git lfs but now i see new problem


```
apt-get install git-lfs
git lfs install
mkdir -p obcq_deployment
mkdir -p deployment
git clone https://huggingface.co/OpenBuddy/openbuddy-mistral-7b-v13 /content/obcq_deployment
```

```
Traceback (most recent call last):
  File "/content/sparseml/src/sparseml/transformers/sparsification/obcq/export.py", line 543, in <module>
    main()
  File "/content/sparseml/src/sparseml/transformers/sparsification/obcq/export.py", line 530, in main
    export(
  File "/content/sparseml/src/sparseml/transformers/sparsification/obcq/export.py", line 508, in export
    export_transformer_to_onnx(
  File "/content/sparseml/src/sparseml/transformers/sparsification/obcq/export.py", line 290, in export_transformer_to_onnx
    model = load_task_model(task, model_path, config, trust_remote_code)
  File "/content/sparseml/src/sparseml/transformers/sparsification/obcq/export.py", line 152, in load_task_model
    return SparseAutoModel.text_generation_from_pretrained(
  File "/content/sparseml/src/sparseml/transformers/utils/sparse_model.py", line 273, in text_generation_from_pretrained
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3085, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: MistralForCausalLM.__init__() got an unexpected keyword argument 'model_type'
```

**Expected behavior**
expected this wiil working)

**Environment**
Include all relevant environment information:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
Python 3.10.12
Install by this tree manual
(https://github.com/neuralmagic/sparseml/tree/main/src/sparseml/transformers/sparsification/obcq)

**Comment by dbogunowicz** [comment]
Hey @meomeomeome, I think we are working on the solution for this problem as we speak. But just for more context:
- what is your sparseml version
- what is the exact command that you are running (I think you failed to attach it to your issue)

**Comment by meomeomeome** [comment]
Hi this problem solved by using env

**Comment by dbogunowicz** [comment]
@meomeomeome great to hear that! Closing.
