### ISSUE TITLE
Class Index change observed when validating a yolov5 pruned sparseml model

### ISSUE THREAD

**Issue by AKSHILMY** [neuralmagic/sparseml#2185]
I trained a yolov5 model using sparseml for a custom dataset and upon validating it after exporting to onnx, I observe the following error.

```
val: data=/content/yolov5/data/coco128.yaml, weights=['/content/model.onnx'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, max_det=300, task=val, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
YOLOv5 🚀 v7.0-294-gdb125a20 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla T4, 15102MiB)

Loading /content/model.onnx for ONNX Runtime inference...
2024-03-16 10:06:15.556416310 [E:onnxruntime:Default, provider_bridge_ort.cc:1548 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

2024-03-16 10:06:15.556446875 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:861 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirementsto ensure all dependencies are met.
Forcing --batch-size 1 square inference (1,3,640,640) for non-PyTorch models
val: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100% 128/128 [00:00<?, ?it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   0% 0/128 [00:00<?, ?it/s]WARNING ⚠️ NMS time limit 0.550s exceeded
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   1% 1/128 [00:01<02:48,  1.32s/it]Exception in thread Thread-2 (plot_images):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/yolov5/utils/plots.py", line 205, in plot_images
    cls = names[cls] if names else cls
KeyError: 45
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   2% 2/128 [00:01<01:37,  1.30it/s]Exception in thread Thread-4 (plot_images):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/yolov5/utils/plots.py", line 205, in plot_images
    cls = names[cls] if names else cls
KeyError: 23
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   2% 3/128 [00:02<01:11,  1.75it/s]Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/yolov5/utils/plots.py", line 205, in plot_images
    cls = names[cls] if names else cls
KeyError: 58
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 128/128 [00:30<00:00,  4.14it/s]
                   all        128        929     0.0373    0.00898     0.0111    0.00509
Speed: 0.4ms pre-process, 221.1ms inference, 8.7ms NMS per image at shape (1, 3, 640, 640)
Exception in thread Thread-9 (plot_mc_curve):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/yolov5/utils/metrics.py", line 369, in plot_mc_curve
    ax.plot(px, y, linewidth=1, label=f"{names[i]}")  # plot(confidence, metric)
KeyError: 17
Exception in thread Thread-10 (plot_mc_curve):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/yolov5/utils/metrics.py", line 369, in plot_mc_curve
    ax.plot(px, y, linewidth=1, label=f"{names[i]}")  # plot(confidence, metric)
KeyError: 17
Exception in thread Thread-11 (plot_mc_curve):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/yolov5/utils/metrics.py", line 369, in plot_mc_curve
    ax.plot(px, y, linewidth=1, label=f"{names[i]}")  # plot(confidence, metric)
KeyError: 17
Results saved to runs/val/exp5
```

Does the sparseml train change any class indices ?  You could access the .pt weight at [https://drive.google.com/drive/u/1/folders/18TMf640W3cj3kxj55d1PVpxUv7HTN4v8](https://drive.google.com/drive/u/1/folders/18TMf640W3cj3kxj55d1PVpxUv7HTN4v8)

**Comment by bfineran** [comment]
hi @AKSHILMY what command are you running? you mention using a custom dataset, but I see that it looks like COCO128 is the dataset that is read from in the stack trace. Thanks!

**Comment by jeanniefinks** [comment]
Hi @AKSHILMY 
As some time has passed with no further updates, I am going to go ahead and close out this issue.
Please re-open if you want to continue the conversation.
Best, Jeannie / Neural Magic
