### ISSUE TITLE
Running out of CUDA memory in quantisation step

### ISSUE THREAD

**Issue by StianHanssen** [neuralmagic/sparseml#369]
**Describe the question**
I recently discovered your work on speeding up YoloV5 on CPU and so I wanted to give it a try on a private dataset. I tried to run the [yolov5.transfer_learn_pruned_quantized recipie](https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/recipes/yolov5.transfer_learn_pruned_quantized.md) and everything works fine until the quantisation epochs start. I am afraid my NVIDIA GeForce GTX 1080 Ti may not have enough memory capacity (around 10 GB).

**I am wondering if you have any tips for me? Is there for example an option to adjust batch size during the quantisation epochs, or would it be better to adjust the batch size for the whole training run? Any suggestions would be much appreciated!**

**Environment**
1. OS: 5.13.7-gentoo
2. Python version: python 3.7
3. SparseML version or commit hash: b1768948d45a3b426d42eafc51b8c73e6de6fdbf
4. ML framework version(s) : torch==1.7.1
5. Other Python package versions: sparsezoo==0.6.0, sparseml==0.6.0, numpy==1.21.2, onnx==1.7.0
6. Other relevant environment information: NVIDIA GeForce GTX 1080 Ti, driver version 470.57.02, CUDA 11.4

**To Reproduce**
Follow this tutorial exactly [Sparse Transfer Learning With YOLOv5](https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/yolov5_sparse_transfer_learning.md) on model `YOLOv5s Pruned Quantized`. Due to my GPU limitations I get the following:

When I start the training I get this warning, which I am unsure if really matters, but to give complete context:
```
/home/stian/miniconda3/envs/yolov5/lib/python3.7/site-packages/sparsezoo/requests/base.py:80: UserWarning: Invalid query string for stub cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggress
ive_94 valid params include [], given ['recipe_type']                                              
  f"Invalid query string for stub {stub} valid params include {valid_params},"
```
Then after epoch 50 when quantisation epochs kick in:
```
Traceback (most recent call last):                                                                                                                                                                          
  File "train.py", line 564, in <module>                                                                                                                                                                    
    train(hyp, opt, device, tb_writer)                                                                                                                                                                      
  File "train.py", line 316, in train                                                                                                                                                                       
    pred = model(imgs)  # forward                                                                     
  File "/home/stian/miniconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                 
    result = self.forward(*input, **kwargs)                                                                                                                                                                 
  File "/home/stian/Projects/sparseml/integrations/ultralytics-yolov5/yolov5/models/yolo.py", line 119, in forward                                                                                          
    return self.forward_once(x, profile)  # single-scale inference, train                                                                                                                                   
  File "/home/stian/Projects/sparseml/integrations/ultralytics-yolov5/yolov5/models/yolo.py", line 150, in forward_once                                                                                     
    x = m(x)  # run                                                                                   
  File "/home/stian/miniconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                 
    result = self.forward(*input, **kwargs)                                                           
  File "/home/stian/Projects/sparseml/integrations/ultralytics-yolov5/yolov5/models/common.py", line 138, in forward                                                                                        
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), dim=1))                                                                                                                                   
  File "/home/stian/miniconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                 
    result = self.forward(*input, **kwargs)                                                           
  File "/home/stian/Projects/sparseml/integrations/ultralytics-yolov5/yolov5/models/common.py", line 42, in forward                                                                                         
    return self.act(self.bn(self.conv(x)))                                                            
  File "/home/stian/miniconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                 
    result = self.forward(*input, **kwargs)                                                           
  File "/home/stian/Projects/sparseml/integrations/ultralytics-yolov5/yolov5/utils/activations.py", line 38, in forward                                                                                     
    return x * F.hardtanh(x + 3, 0., 6.) / 6.  # for torchscript, CoreML and ONNX                     
  File "/home/stian/miniconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/functional.py", line 1188, in hardtanh                                                                                      
    result = torch._C._nn.hardtanh(input, min_val, max_val)                                           
RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 10.92 GiB total capacity; 9.99 GiB already allocated; 12.69 MiB free; 10.22 GiB reserved in total by PyTorch)
```

**Comment by StianHanssen** [comment]
Apologies, I just found the note:

> When running quantized models, the memory footprint for training will significantly increase (roughly 3x). It is recommended to train at a high batch size at first. This will fail with an out-of-memory exception once quantization starts. Once this happens, use the last.pt weights from that run to resume training with a lower batch size.

I will follow this reccommendation

**Comment by markurtz** [comment]
Hi @StianHanssen, glad you found that note! Let us know if you run into any other issues and we're happy to help.
