### ISSUE TITLE
DimensionSparsityMaskCreator creates unexpected mask_type

### ISSUE THREAD

**Issue by clementpoiret** [neuralmagic/sparseml#441]
**Describe the bug**
When using a recipe, using the parameter mask_type: unstructured works as expected:

```yaml
    - !GMPruningModifier
        mask_type: unstructured
```

But according to the doc, we can choose to use "channel" or "filter" for structured pruning, and here is the problem.
When using either of those, we have an error saying we can't iterate on a string at the line `reduced_dims = [idx for idx in range(n_dims) if idx not in self._dim]`

`self._dim` is defined in the `__init__` of `DimensionSparsityMaskCreator`.
But, it is overriden:

```python
...
        if isinstance(dim, str):
            valid_dim_names = ["channel", "filter"]
            if dim in valid_dim_names:
                self._dim_name = dim
                self._dim = [1] if dim == "channel" else [0, 1]
...
        self._dim = dim  # List[int]
```
But `dim` is either "channel" or "filter", meaning that we can't define `reduced_dims`.

ALSO, something strange is that when using `mask_type: 1` (I expected to trigger the following code)

```python
        if isinstance(dim, int):
            dim = [dim]
```

I get the error telling me: 

```
File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/mask_creator_pruning.py", line 619, in load_mask_creator
    if ("[" in obj and "]" in obj) or ("(" in obj and ")" in obj):
TypeError: argument of type 'int' is not iterable
```

**Expected behavior**

As indicated in the docstrings, mask_type should accept channel, filter, int or List[int], in addition to "unstructured"

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: RedHat
2. Python version [e.g. 3.7]: 3.8
3. SparseML version or commit hash [e.g. 0.1.0, `f7245c8`]: 0.8.0
4. ML framework version(s) [e.g. torch 1.7.1]: Torch 1.9.0
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]:

**To Reproduce**

Exact steps to reproduce the behavior:
1. Define a model,
2. Try to train it with a recipe GMPruningModifier, mask_type: channel

**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.

mask_type: channel

```
File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/manager.py", line 160, in step
    return self._perform_wrapped_step(*args, **kwargs)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/manager.py", line 198, in _perform_wrapped_step
    self._wrapped_manager.update(
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/manager.py", line 448, in update
    mod.scheduled_update(module, optimizer, epoch, steps_per_epoch)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/modifier.py", line 519, in scheduled_update
    self.update(module, optimizer, epoch, steps_per_epoch)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/modifier_pruning.py", line 277, in update
    self._check_mask_update(module, epoch, steps_per_epoch)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/modifier_pruning.py", line 761, in _check_mask_update
    self._module_masks.set_param_masks_from_sparsity(self._applied_sparsity)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/mask_pruning.py", line 383, in set_param_masks_from_sparsity
    masks = self._mask_creator.create_sparsity_masks(
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/mask_creator_pruning.py", line 443, in create_sparsity_masks
    return super().create_sparsity_masks(tensors, sparsity, global_sparsity=False)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/mask_creator_pruning.py", line 373, in create_sparsity_masks
    grouped_tensors = [self.group_tensor(tensor) for tensor in tensors]
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/mask_creator_pruning.py", line 373, in <listcomp>
    grouped_tensors = [self.group_tensor(tensor) for tensor in tensors]
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/mask_creator_pruning.py", line 456, in group_tensor
    reduced_dims = [idx for idx in range(n_dims) if idx not in self._dim]
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/mask_creator_pruning.py", line 456, in <listcomp>
    reduced_dims = [idx for idx in range(n_dims) if idx not in self._dim]
TypeError: 'in <string>' requires string as left operand, not int
```

mask_type: 1:

```
Traceback (most recent call last):
  File "experiment_sparseml.py", line 176, in <module>
    main()
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "experiment_sparseml.py", line 112, in main
    callbacks=[SparseMLCallback(recipe_path='/gpfswork/rech/dod/uuj72kc/bagginghsf/sparsify_70_qat_channel.yaml')],
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/pl_bolts/callbacks/sparseml.py", line 42, in __init__
    self.manager = ScheduledModifierManager.from_yaml(recipe_path)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/manager.py", line 269, in from_yaml
    modifiers = Modifier.load_list(yaml_str)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/modifier.py", line 90, in load_list
    return Modifier.load_framework_list(yaml_str, PYTORCH_FRAMEWORK)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/optim/modifier.py", line 294, in load_framework_list
    container = yaml.safe_load(yaml_str)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/optim/modifier.py", line 760, in constructor
    instance.__init__(**state)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/modifier_pruning.py", line 545, in __init__
    else load_mask_creator(mask_type)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/optim/mask_creator_pruning.py", line 619, in load_mask_creator
    if ("[" in obj and "]" in obj) or ("(" in obj and ")" in obj):
TypeError: argument of type 'int' is not iterable
```

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by bfineran** [comment]
Hi @clementpoiret thank you for finding and fixing this bug. I've approved #442 and will get that landed.

We're currently overhauling our structure pruning support including for filter pruning which is reducing the wrong dimensions (should be `[0]` instead of `[0,1]`) and adding support for pruning groups of parameters together (#440).

**Comment by clementpoiret** [comment]
Thanks for the information @bfineran 
As I am using sparseml to prune and quantize my models, does it mean I have to change (at least locally) [0,1] by [0] to have the expected filter pruning? Or is it better to wait until 0.9.0?

**Comment by markurtz** [comment]
Hi @clementpoiret, we'd recommend waiting until 0.9 for better-structured pruning support. This should go out in the next two weeks and we'll keep you updated as this progresses.

**Comment by jeanniefinks** [comment]
Hi @clementpoiret 
Release .9 has gone out the door; we hope you can try our latest version to address this issue; a summary of release highlights is also available - check them out here: [](https://neuralmagic.com/blog/neural-magic-ce-0-7-0-8-and-0-9-product-releases/)

Best, Jeannie / Neural Magic

**Comment by markurtz** [comment]
Hi @clementpoiret to follow up on the comment from @jeanniefinks, we have added a StructuredPruningModifier in the 0.9 release for PyTorch. Let us know if you have a chance to try it out as this enables proper filter pruning. Happy to help walkthrough an example as well!

Thanks,
Mark

**Comment by clementpoiret** [comment]
I launched another training using StructuredPruningModifier to prune filters, but some questions are coming to my mind:
1/ In the doc, GMPruningModifier still have "filters" and "channels". Is it now equivalent to using the StructuredPruningModifier with the same arguments?
2/ How can I check if the model is correctly pruned? The final pruned ONNX file weights the same thing (around 140Mb) than its non-pruned counterpart, is this normal?

Thanks!
