### ISSUE TITLE
`quantize_torch_qat_export` can't load model: Error parsing message with type 'onnx.ModelProto'

### ISSUE THREAD

**Issue by clementpoiret** [neuralmagic/sparseml#443]
**Describe the bug**

I am training a segmentation model with pruning and quantization. While exporting the model, I pass `convert_qat=True` because I assume it is not optimal to bring a fake quantized model into production.

The strange thing is that the model I get in my output folder *seems* correctly converted...

As soon as it tries to execute `quantize_torch_qat_export`, I get the following error:

```
Error executing job with overrides: ['datasets.main_path=/gpfsscratch/rech/dod/uuj72kc/datasets/', 'datasets.num_workers=1', 'lightning.default_root_dir=/gpfswork/rech/dod/uuj72kc/bagginghsf', 'lightning.stochastic_weight_avg=False']
Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/dod/uuj72kc/bagginghsf/experiment_sparseml.py", line 176, in <module>
    main()
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/gpfsdswork/projects/rech/dod/uuj72kc/bagginghsf/experiment_sparseml.py", line 150, in main
    SparseMLCallback.export_to_sparse_onnx(model,
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/pl_bolts/callbacks/sparseml.py", line 94, in export_to_sparse_onnx
    exporter.export_onnx(sample_batch=sample_batch, **export_kwargs)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/utils/exporter.py", line 192, in export_onnx
    export_onnx(
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/utils/exporter.py", line 468, in export_onnx
    quantize_torch_qat_export(model=file_path, output_file_path=file_path)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/sparseml/pytorch/utils/quantization/quantize_qat_export.py", line 1081, in quantize_torch_qat_export
    model = onnx.load(model)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/onnx/__init__.py", line 121, in load_model
    model = load_model_from_string(s, format=format)
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/onnx/__init__.py", line 158, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "/gpfswork/rech/dod/uuj72kc/anaconda3/envs/SparseML/lib/python3.8/site-packages/onnx/__init__.py", line 99, in _deserialize
    decoded = cast(Optional[int], proto.ParseFromString(s))
google.protobuf.message.DecodeError: Error parsing message with type 'onnx.ModelProto'
```

***Full log if needed***: http://pastebin.fr/97220 (sorry, it's quite long and verbose)

If it can help, **here is the model I am left with**, I assume it is the one that is saved right before the call of `quantize_torch_cat_export`: https://filebin.net/wqm5kv6ohorsmc2q (will be deleted automatically in 6 days, if needed I can reupload it)

**Expected behavior**

Well, convert a fake quantized model to a fully quantized model I think :)

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: RedHat
2. Python version [e.g. 3.7]: 3.8
3. SparseML version or commit hash [e.g. 0.1.0, `f7245c8`]: 0.8.0
4. ML framework version(s) [e.g. torch 1.7.1]: Torch 1.9.0
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]: Distributed Data Parallel with PyTorch Lightning on 8 NVidia A100 GPUs

**To Reproduce**
Exact steps to reproduce the behavior:

1. Train a model with a QAT recipe,
2. export using `convert_qat=True`

**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.

***Full log if needed***: http://pastebin.fr/97220 (sorry, it's quite long and verbose)

**Comment by markurtz** [comment]
Hi @clementpoiret, we'll look into this further. Additionally, do you have any more info that you could provide on the integration or recipe that was used for it? Also, if we had a reproducible run of the model in PyTorch exporting to ONNX that would help quite a bit for us trying to reproduce the issue and get a fix in.

Also, with our next release, we're going to be pushing out a pruned and quantized YOLACT model as our first officially supported segmentation model. We'll update here once that goes out to see if that meets your needs as well.

**Comment by jeanniefinks** [comment]
Hi @clementpoiret 
We wanted to let you know we recently released [our YOLACT integration](https://github.com/neuralmagic/sparseml/tree/main/integrations/dbolya-yolact).  Let us know what you think?

Also if you had more details to provide per Mark's last comment, we're happy to assist.

Regards, Jeannie / Neural Magic

**Comment by clementpoiret** [comment]
I'll take a look at it, thanks! :)

**Comment by jeanniefinks** [comment]
Hi @clementpoiret 
As there has been no response, I am going to go ahead and close this thread out. But if you have more comments, please re-open and we'd love to chat. Lastly, if you have not starred our sparseml repo already, and you feel inclined, pleased do! Thank you in advance for your support! [https://github.com/neuralmagic/sparseml/](https://github.com/neuralmagic/sparseml/ )

Best, Jeannie / Neural Magic
