### ISSUE TITLE
ONNx model error

### ISSUE THREAD

**Issue by devendraswamy** [neuralmagic/sparseml#490]
after export the model in windows system getting this error 

ERROR: Invalid requirement: "'torch~=1.7.0'"
ERROR: Invalid requirement: "'torchvision"
YOLOv5  v5.0-148-g63b9a73 torch 1.7.0 CPU

Traceback (most recent call last):
  File "detect.py", line 184, in <module>
    detect(opt=opt)
  File "detect.py", line 33, in detect
    model, extras = load_checkpoint('ensemble', weights, device)  # load FP32 model
  File "D:\yolo_pruning\From_gc\Yolo_pruning\sparseml\integrations\ultralytics-yolov5\yolov5\models\export.py", line 57, in load_checkpoint
    else weights, map_location=device)  # load checkpoint
  File "C:\Users\AppsTekO22\miniconda3\envs\yolo_inf_py3.7.0\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\AppsTekO22\miniconda3\envs\yolo_inf_py3.7.0\lib\site-packages\torch\serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.

ERROR: Invalid requirement: "'torch~=1.7.0'"
ERROR: Invalid requirement: "'torchvision"
YOLOv5  v5.0-148-g63b9a73 torch 1.7.0 CPU

getting error for convverted .pt file

C:\Users\AppsTekO22\miniconda3\envs\yolo_inf_py3.7.0\lib\site-packages\torch\serialization.py:591: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  " silence this warning)", UserWarning)
Traceback (most recent call last):
  File "detect.py", line 184, in <module>
    detect(opt=opt)
  File "detect.py", line 33, in detect
    model, extras = load_checkpoint('ensemble', weights, device)  # load FP32 model
  File "D:\yolo_pruning\From_gc\Yolo_pruning\sparseml\integrations\ultralytics-yolov5\yolov5\models\export.py", line 58, in load_checkpoint
    start_epoch = ckpt['epoch'] + 1 if 'epoch' in ckpt else 0
  File "C:\Users\AppsTekO22\miniconda3\envs\yolo_inf_py3.7.0\lib\site-packages\torch\jit\_script.py", line 624, in __contains__
    return self.forward_magic_method("__contains__", key)
  File "C:\Users\AppsTekO22\miniconda3\envs\yolo_inf_py3.7.0\lib\site-packages\torch\jit\_script.py", line 611, in forward_magic_method
    raise NotImplementedError()
NotImplementedError

Please help me , Thank you

**Comment by jeanniefinks** [comment]
Hi @devendraswamy 
Note that our software requires running on the Linux operating system; please review [https://docs.neuralmagic.com/deepsparse/source/hardware.html](https://docs.neuralmagic.com/deepsparse/source/hardware.html). We find our users go with WSL/Windows Subsystem for Linux or running a VM on top of Windows. We hope you can try that option and let us know if you still encounter issues.

Best, Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
Hello @devendraswamy 
As it has been some time without a response, I am going to go ahead and close this comment. Please re-open if you have a follow-up. Also, I invite you to "star" our SparseML repo if you like and have not already! We always like seeing the community support!
[https://github.com/neuralmagic/sparseml/](https://github.com/neuralmagic/sparseml/)

Thank you!
Jeannie / Neural Magic
