### ISSUE TITLE
Before last epoch quantization phase - out of memory 

### ISSUE THREAD

**Issue by mate-hegedus** [neuralmagic/sparseml#923]
**Describe the bug**
Before last epoch training stops with:
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 10.91 GiB total capacity; 9.33 GiB already allocated; 10.94 MiB free; 9.93 GiB reserved in total by PyTorch)

**Expected behavior**

According to https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/sparsifying_yolov5_using_recipes.md i got through the first phase and trained YOLOv5l with this:
python train.py --cfg ../models_v5.0/yolov5l.yaml --weights "" --data coco.yaml --hyp data/hyps/hyp.scratch.yaml --batch-size -1

Then: training with this: 
python train.py --cfg ../models_v5.0/yolov5l.yaml --weights PATH_TO_COCO_PRETRAINED_WEIGHTS --data coco.yaml --hyp data/hyps/hyp.scratch.yaml --recipe ../recipes/yolov5l.pruned_quantized.md --batch-size -1

**Environment**
Include all relevant environment information:
Ubuntu 18.04
Python version 3.8
SparseML version or commit hash [e.g. 0.1.0, f7245c8]:
ML framework version 1.9.1+cu102
1080ti

**To Reproduce**
I only changed the yolov5l.pruned_quantized.md in the following line (however with the original numbers i got the same error as well)
num_epochs: &num_epochs 50
pruning_end_epoch: &pruning_end_epoch 30
quantization_start_epoch: &quantization_start_epoch 48

**Errors**
     Epoch   gpu_mem       box       obj       cls    labels  img_size
     47/49     9.95G   0.02326  0.008135         0         3       640: 100%|██████████| 1135/1135 [14:52<00:00,  1.27it/s]                                                               
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 13/13 [00:04<00:00,  2.77it/s]                                                   
                 all        231        300      0.934       0.94       0.97       0.75
Disabling half precision and EMA, QAT scheduled to run

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/1135 [00:00<?, ?it/s]                                                                                                                                                  
Traceback (most recent call last):
  File "train.py", line 681, in <module>
    main(opt)
  File "train.py", line 577, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 356, in train
    pred = model(imgs)  # forward
  File "/home/mate/Developer/recog/yolov5-neural/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mate/Developer/recog/yolov5-neural/sparseml/integrations/ultralytics-yolov5/yolov5/models/yolo.py", line 128, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/mate/Developer/recog/yolov5-neural/sparseml/integrations/ultralytics-yolov5/yolov5/models/yolo.py", line 151, in _forward_once
    x = m(x)  # run
  File "/home/mate/Developer/recog/yolov5-neural/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mate/Developer/recog/yolov5-neural/sparseml/integrations/ultralytics-yolov5/yolov5/models/common.py", line 139, in forward
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), dim=1))
  File "/home/mate/Developer/recog/yolov5-neural/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mate/Developer/recog/yolov5-neural/venv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/mate/Developer/recog/yolov5-neural/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mate/Developer/recog/yolov5-neural/sparseml/integrations/ultralytics-yolov5/yolov5/models/common.py", line 105, in forward
    return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))
  File "/home/mate/Developer/recog/yolov5-neural/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mate/Developer/recog/yolov5-neural/sparseml/integrations/ultralytics-yolov5/yolov5/models/common.py", line 47, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/mate/Developer/recog/yolov5-neural/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mate/Developer/recog/yolov5-neural/sparseml/integrations/ultralytics-yolov5/yolov5/utils/activations.py", line 39, in forward
    return x * F.hardtanh(x + 3, 0.0, 6.0) / 6.0  # for TorchScript, CoreML and ONNX

**Additional context**
Add any other context about the problem here. Also include any relevant files.

Thank you for your support!

**Comment by KSGulin** [comment]
Hi @mate-hegedus, this occurs because QAT requires additional memory overhead during training, which means autobatch may cause an OOM error when running with QAT. With ~10GB memory, you may want to use a batch size of 8 to accommodate QAT (this is just an estimate, the actual value may vary).

Note that YOLOv5 accumulates batches into an effective batch size of 64, so this will not impact the accuracy of your resulting model.
