### ISSUE TITLE
SparseML YOLOv5 install loop 

### ISSUE THREAD

**Issue by rahul-tuli** [neuralmagic/sparseml#991]
**Describe the bug**
Invoking `sparseml.yolov5` command line callable (for example `sparseml.yolov5.export_onnx --help`) repeatedly fails to install `sparseml-yolov5` dependencies on a bare metal server if binaries needed for `opencv` are not found. 

**Expected behavior**
`sparseml-yolov5` dependencies install without error, or display an apt error message pointing out the right installation error

**Environment**
Include all relevant environment information:
1. OS: `Ubuntu 20.04.4 LTS`
2. Python version: `Python 3.8`
3. SparseML version or commit hash: `45e9d3b73a`
4. ML framework version(s): `1.9.1`
5. Other Python package versions: `sparsezoo-nightly 1.1.0.20220810`
6. Other relevant environment information: 

```bash
GenuineIntel CPU detected with 24 cores. (1 sockets with 24 cores each)
DeepSparse FP32 model performance supported: True.
DeepSparse INT8 (quantized) model performance supported: TRUE.

Additional CPU info: {'L1_data_cache_size': 49152, 'L1_instruction_cache_size': 32768, 'L2_cache_size': 1310720, 'L3_cache_size': 56623104, 'architecture': 'x86_64', 'available_cores_per_socket': 24, 'available_num_cores': 24, 'available_num_hw_threads': 48, 'available_num_numa': 1, 'available_num_sockets': 1, 'available_sockets': 1, 'available_threads_per_core': 2, 'bf16': False, 'cores_per_socket': 24, 'isa': 'avx512', 'num_cores': 24, 'num_hw_threads': 48, 'num_numa': 1, 'num_sockets': 1, 'threads_per_core': 2, 'vendor': 'GenuineIntel', 'vendor_id': 'Intel', 'vendor_model': 'Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz', 'vnni': True}
```

**To Reproduce**

STEP 1: Remove opencv dependencies (using `apt`). Might need `sudo`

```bash
apt remove libglu1-mesa libxi-dev libxmu-dev libglu1-mesa-dev libopencv-dev python3-opencv
```

STEP 2: Clone and install sparseml

```bash
git clone https://github.com/neuralmagic.sparseml.git && \
cd sparseml && pip install -e "./[torchvision]"
```

STEP 3: invoke a sparseml.yolov5 callable

```bash
sparseml.yolov5.export_onnx --help
```

**Errors**
```
(.venv) ubuntu@ip-172-31-27-161:~/sparseml$ sparseml.yolov5.export_onnx --help
2022-08-15 05:08:55 sparseml.yolov5 WARNING  sparseml-yolov5 installation not detected. Installing sparseml-yolov5 dependencies if yolov5 is already installed in the environment, it will be overwritten. Set environment variable NM_NO_AUTOINSTALL_YOLOV5 to disable
Requirement already satisfied: yolov5==6.1.0 from https://github.com/neuralmagic/yolov5/releases/download/nightly/yolov5-6.1.0-py3-none-any.whl in ./.venv/lib/python3.8/site-packages (6.1.0)
Requirement already satisfied: scipy>=1.4.1 in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (1.9.0)
Requirement already satisfied: numpy>=1.18.5 in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (1.23.2)
Requirement already satisfied: tqdm>=4.41.0 in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (4.64.0)
Requirement already satisfied: tensorboard>=2.4.1 in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (2.8.0)
Requirement already satisfied: Pillow>=7.1.2 in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (9.2.0)
Requirement already satisfied: pandas>=1.1.4 in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (1.4.3)
Requirement already satisfied: matplotlib>=3.2.2 in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (3.5.3)
Requirement already satisfied: requests>=2.23.0 in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (2.28.1)
Requirement already satisfied: opencv-python>=4.1.2 in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (4.6.0.66)
Requirement already satisfied: PyYAML>=5.3.1 in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (6.0)
Requirement already satisfied: thop in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (0.1.1.post2207130030)
Requirement already satisfied: seaborn>=0.11.0 in ./.venv/lib/python3.8/site-packages (from yolov5==6.1.0) (0.11.2)
Requirement already satisfied: protobuf>=3.6.0 in ./.venv/lib/python3.8/site-packages (from tensorboard>=2.4.1->yolov5==6.1.0) (3.20.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in ./.venv/lib/python3.8/site-packages (from tensorboard>=2.4.1->yolov5==6.1.0) (2.10.0)
Requirement already satisfied: grpcio>=1.24.3 in ./.venv/lib/python3.8/site-packages (from tensorboard>=2.4.1->yolov5==6.1.0) (1.47.0)
Requirement already satisfied: absl-py>=0.4 in ./.venv/lib/python3.8/site-packages (from tensorboard>=2.4.1->yolov5==6.1.0) (1.2.0)
Requirement already satisfied: setuptools>=41.0.0 in ./.venv/lib/python3.8/site-packages (from tensorboard>=2.4.1->yolov5==6.1.0) (44.0.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./.venv/lib/python3.8/site-packages (from tensorboard>=2.4.1->yolov5==6.1.0) (0.4.6)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in ./.venv/lib/python3.8/site-packages (from tensorboard>=2.4.1->yolov5==6.1.0) (0.6.1)
Requirement already satisfied: wheel>=0.26 in ./.venv/lib/python3.8/site-packages (from tensorboard>=2.4.1->yolov5==6.1.0) (0.37.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in ./.venv/lib/python3.8/site-packages (from tensorboard>=2.4.1->yolov5==6.1.0) (1.8.1)
Requirement already satisfied: markdown>=2.6.8 in ./.venv/lib/python3.8/site-packages (from tensorboard>=2.4.1->yolov5==6.1.0) (3.4.1)
Requirement already satisfied: werkzeug>=0.11.15 in ./.venv/lib/python3.8/site-packages (from tensorboard>=2.4.1->yolov5==6.1.0) (2.2.2)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.8/site-packages (from pandas>=1.1.4->yolov5==6.1.0) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.8.1 in ./.venv/lib/python3.8/site-packages (from pandas>=1.1.4->yolov5==6.1.0) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in ./.venv/lib/python3.8/site-packages (from matplotlib>=3.2.2->yolov5==6.1.0) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.venv/lib/python3.8/site-packages (from matplotlib>=3.2.2->yolov5==6.1.0) (1.4.4)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.8/site-packages (from matplotlib>=3.2.2->yolov5==6.1.0) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.8/site-packages (from matplotlib>=3.2.2->yolov5==6.1.0) (4.34.4)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.8/site-packages (from matplotlib>=3.2.2->yolov5==6.1.0) (0.11.0)
Requirement already satisfied: charset-normalizer<3,>=2 in ./.venv/lib/python3.8/site-packages (from requests>=2.23.0->yolov5==6.1.0) (2.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.venv/lib/python3.8/site-packages (from requests>=2.23.0->yolov5==6.1.0) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.8/site-packages (from requests>=2.23.0->yolov5==6.1.0) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.8/site-packages (from requests>=2.23.0->yolov5==6.1.0) (2022.6.15)
Requirement already satisfied: torch in ./.venv/lib/python3.8/site-packages (from thop->yolov5==6.1.0) (1.9.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.venv/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.4.1->yolov5==6.1.0) (5.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.venv/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.4.1->yolov5==6.1.0) (0.2.8)
Requirement already satisfied: six>=1.9.0 in ./.venv/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.4.1->yolov5==6.1.0) (1.16.0)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in ./.venv/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.4.1->yolov5==6.1.0) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.venv/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.4.1->yolov5==6.1.0) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4; python_version < "3.10" in ./.venv/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard>=2.4.1->yolov5==6.1.0) (4.12.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in ./.venv/lib/python3.8/site-packages (from werkzeug>=0.11.15->tensorboard>=2.4.1->yolov5==6.1.0) (2.1.1)
Requirement already satisfied: typing-extensions in ./.venv/lib/python3.8/site-packages (from torch->thop->yolov5==6.1.0) (4.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./.venv/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.4.1->yolov5==6.1.0) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in ./.venv/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.4.1->yolov5==6.1.0) (3.2.0)
Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.8/site-packages (from importlib-metadata>=4.4; python_version < "3.10"->markdown>=2.6.8->tensorboard>=2.4.1->yolov5==6.1.0) (3.8.1)
Traceback (most recent call last):
  File "/home/ubuntu/sparseml/src/sparseml/yolov5/__init__.py", line 64, in _install_yolov5_and_deps
    import yolov5 as _yolov5
  File "/home/ubuntu/sparseml/.venv/lib/python3.8/site-packages/yolov5/__init__.py", line 1, in <module>
    from yolov5.utils.general import NM_INTEGRATED
  File "/home/ubuntu/sparseml/.venv/lib/python3.8/site-packages/yolov5/utils/general.py", line 26, in <module>
    import cv2
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/sparseml/.venv/bin/sparseml.yolov5.export_onnx", line 33, in <module>
    sys.exit(load_entry_point('sparseml-nightly', 'console_scripts', 'sparseml.yolov5.export_onnx')())
  File "/home/ubuntu/sparseml/.venv/bin/sparseml.yolov5.export_onnx", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/sparseml/src/sparseml/yolov5/__init__.py", line 108, in <module>
    _check_yolov5_install()
  File "/home/ubuntu/sparseml/src/sparseml/yolov5/__init__.py", line 93, in _check_yolov5_install
    _install_yolov5_and_deps()
  File "/home/ubuntu/sparseml/src/sparseml/yolov5/__init__.py", line 68, in _install_yolov5_and_deps
    raise ValueError(
ValueError: Unable to install and import sparseml-yolov5 dependencies check that yolov5 is installed, if not, install via `pip install https://github.com/neuralmagic/yolov5/releases/download/nightly/yolov5-6.1.0-py3-none-any.whl`
```

**Additional context**
Noting the invocation fails with the same error message even after a `pip install https://github.com/neuralmagic/yolov5/releases/download/nightly/yolov5-6.1.0-py3-none-any.whl`; 

```bash
(.venv) ubuntu@ip-172-31-27-161:~/sparseml$ pip show torchvision
Name: torchvision
Version: 0.10.1
Summary: image and video datasets and models for torch deep learning
Home-page: https://github.com/pytorch/vision
Author: PyTorch Core Team
Author-email: soumith@pytorch.org
License: BSD
Location: /home/ubuntu/sparseml/.venv/lib/python3.8/site-packages
Requires: pillow, numpy, torch
Required-by:
```

The error does not show up if the binaries needed by `opencv` are installed manually using
`apt install libopencv-dev python3-opencv` (Might need sudo)

**Comment by KSGulin** [comment]
Thanks for unearthing this @rahul-tuli. It seems that this is a well documented issue for using `opencv-python` in a headless environment. There are essentially 2 solution routes, neither of which would be a good idea for us to implement as an automatic step
1. Install the missing cv dependencies using `apt-get`
2. Install opencv-python-headless instead of opencv-python. The headless version avoids a chain of dependence for GUI support, which isn't needed for headless servers. However, users that need GUI functionality won't have it and commands such as `cv2.imgshow()` won't work. 
Since this is a well documented cv2 error that is not unique to sparseml or yolov5, I'm opting to forgo a patch on our end. Thoughts @bfineran?

**Comment by corey-nm** [comment]
+1 on not patching anything on our end. just having this issue with these details should be enough for users to find/fix the problem IMO
