### ISSUE TITLE
Issue trying to reproduce yolov3 sparsification

### ISSUE THREAD

**Issue by dshirron2** [neuralmagic/sparseml#994]
i get:
Exception has occurred: TypeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
_logging_lambda() got an unexpected keyword argument 'tag'

**Expected behavior**

**Environment**
Include all relevant environment information:
1. OS: ubuntu 22.04
2. Python version 3.9.13
3. SparseML version or commit hash: 1.0.1
4. ML framework version(s) [e.g. torch 1.7.1]: 1.7.1+cu110
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]:

**To Reproduce**
1) created a virtual environment
2) Followed instructions on: https://github.com/neuralmagic/sparseml/tree/main/integrations/ultralytics-yolov3

**Errors**
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/neuronix/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/neuronix/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/neuronix/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/neuronix/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/neuronix/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/neuronix/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/neuronix/dan/models/src/sparseml/integrations/ultralytics-yolov3/yolov3/train.py", line 565, in <module>
    train(hyp, opt, device, tb_writer)
  File "/home/neuronix/dan/models/src/sparseml/integrations/ultralytics-yolov3/yolov3/train.py", line 328, in train
    scaler.step(optimizer)  # optimizer.step
  File "/home/neuronix/venv/neuralmagic_sparseml/lib/python3.9/site-packages/sparseml/pytorch/optim/manager.py", line 172, in step
    return self._perform_wrapped_step(*args, **kwargs)
  File "/home/neuronix/venv/neuralmagic_sparseml/lib/python3.9/site-packages/sparseml/pytorch/optim/manager.py", line 210, in _perform_wrapped_step
    self._wrapped_manager.update(
  File "/home/neuronix/venv/neuralmagic_sparseml/lib/python3.9/site-packages/sparseml/pytorch/optim/manager.py", line 592, in update
    mod.scheduled_log_update(module, optimizer, epoch, steps_per_epoch)
  File "/home/neuronix/venv/neuralmagic_sparseml/lib/python3.9/site-packages/sparseml/pytorch/sparsification/modifier.py", line 666, in scheduled_log_update
    self.log_update(module, optimizer, epoch, steps_per_epoch)
  File "/home/neuronix/venv/neuralmagic_sparseml/lib/python3.9/site-packages/sparseml/pytorch/sparsification/pruning/modifier_pruning_base.py", line 406, in log_update
    self.log_scalar(
  File "/home/neuronix/venv/neuralmagic_sparseml/lib/python3.9/site-packages/sparseml/pytorch/sparsification/modifier.py", line 730, in log_scalar
    loggers.log_scalar(tag=tag, value=value, step=step, level=level)
  File "/home/neuronix/venv/neuralmagic_sparseml/lib/python3.9/site-packages/sparseml/pytorch/utils/logger.py", line 867, in log_scalar
    log.log_scalar(
  File "/home/neuronix/venv/neuralmagic_sparseml/lib/python3.9/site-packages/sparseml/pytorch/utils/logger.py", line 729, in log_scalar
    logger.log_scalar(tag, value, step, wall_time, level)
  File "/home/neuronix/venv/neuralmagic_sparseml/lib/python3.9/site-packages/sparseml/pytorch/utils/logger.py", line 273, in log_scalar
    return self._lambda_func(
TypeError: _logging_lambda() got an unexpected keyword argument 'tag'

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by KSGulin** [comment]
Hi @dshirron2, thank you for reporting this bug. A PR to fix this issue is up [here](https://github.com/neuralmagic/yolov3/pull/18) and should land soon. Our main supported pathway for object detection sparsification is yolov5, so if you're considering upgrading to v5 here's another good reason 🙂 

Let us know if you run into any more issues!
